services:
  gateway:
    build: .
    container_name: tis-gateway
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=Asia/Jakarta
    env_file:
      - .env
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
      - /sys/class/gpio:/sys/class/gpio
    network_mode: host
    init: true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
